Patched the user agent core onInvite to interfere when DND is on
open-voip-alliance/WebphoneLib pull request #76
Opened 2020-12-15 10:36 UTC by patrickswijgman

### Issue number

#75 

### Description of fix

Patched the onInvite delegate of the UserAgentCore when instantiating a UserAgent to reject an IncomingInviteRequest early when DND is on. Of course the fix like it is only works for SIP 0.15.x because in 0.16.0 the User Agent has been refactored again.

2020-12-15 15:38 UTC, Dagg-h commented
lgtm :)

2020-12-17 12:37 UTC, confususs requested changes

2020-12-17 12:37 UTC, confususs commented on demo/components/c-contacts.mjs
> +                    await sipClient.subscribe(this.nodes.input.value);
You could re-use accountId here :)

2020-12-17 12:37 UTC, confususs commented on demo/components/c-contacts.mjs
> +                    contactNode.data = { contactUri: this.nodes.input.value };
Same here

2020-12-17 12:37 UTC, confususs commented on test/client-disconnect.ts
>      await (client as any).transport.disconnect({ hasRegistered: false });
If you remove the async / await and return the `transport.disconnect({..})` the linter will probably be happy & you can remove the disable-next-line

2020-12-23 08:35 UTC, patrickswijgman commented
Closing this in favour of https://github.com/open-voip-alliance/WebphoneLib/pull/80

2020-12-23 08:35 UTC, closed without merging